version: '3.8'

x-base:
  &base
  networks:
    - beauty_shop_network
  restart: always

services:
  postgres:
    <<: *base
    image: postgres:17
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - beauty_shop_database:/var/lib/postgresql/data

### local
  svc_beauty:
    <<: *base
    build: ./containers/svc_beauty
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    volumes:
      - ./services/svc_beauty/app:/app
      - ./services/svc_beauty/app/node_modules:/node_modules

volumes:
  beauty_shop_database:

networks:
  beauty_shop_network: